[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.0",
    "pandas>=2.3.1",
    "pillow>=10.0.0",
    "plotly>=6.2.0",
    "requests>=2.32.4",
    "streamlit>=1.28.0",
]
